"""Generate the two API reference artifacts the docs site publishes, from the running app.

  docs/site/reference/openapi.json  — `app.openapi()`, the REST contract (rendered by Swagger
                                       UI on the REST API page; input for the future client SDK)
  docs/site/reference/mcp-tools.md  — every MCP tool with its declared authorization gate and the
                                       first paragraph of its LLM-facing description, grouped the
                                       way the docs count them (read-only / changes state /
                                       live probe)

Needs the backend environment (imports the FastAPI app and the MCP server), so the drift guard
is a CI step in the backend job, not a pre-commit hook:

    python -m backend.scripts.export_docs_reference          # regenerate
    python -m backend.scripts.export_docs_reference --check  # exit 1 if either file is stale
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPENAPI_OUT = ROOT / "docs/site/reference/openapi.json"
MCP_OUT = ROOT / "docs/site/reference/mcp-tools.md"

#: Gated like writes, but persist nothing: each opens a live datasource with a stored credential.
LIVE_PROBE_TOOLS = frozenset(
    {"dryrun_check", "list_columns", "profile_column", "suggest_column_policy", "test_connection"}
)
#: gate -> (who can call it, read-only?). A gate missing here fails the build, so a new gate
#: value gets classified deliberately rather than by string shape.
GATES_DOC: dict[str, tuple[str, bool]] = {
    "read": ("any signed-in user", True),
    "read:suite-optional": ("any signed-in user; suite-scoped when a suite is named", True),
    "suite:view": ("`view` on the suite", True),
    "suite:edit": ("`edit` on the suite", False),
    "incident:view": ("`view` on the incident's suite", True),
    "incident:edit": ("`edit` on the incident's suite", False),
    "role:member": ("workspace Member or Admin", False),
}


def _first_paragraph(text: str) -> str:
    para = text.strip().split("\n\n", 1)[0]
    return " ".join(line.strip() for line in para.splitlines())


def build_openapi() -> str:
    from backend.app.main import app

    return json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"


def build_mcp_tools() -> str:
    from backend.app.mcp.server import mcp
    from backend.tests.support.mcp_gates import GATES

    tools = {t.name: t for t in asyncio.run(mcp.list_tools())}
    missing = set(tools) ^ set(GATES)
    if missing:
        raise SystemExit(f"GATES and the registered tools disagree: {sorted(missing)}")
    unknown_gates = {g for g in GATES.values() if g not in GATES_DOC}
    if unknown_gates:
        raise SystemExit(f"classify gate(s) {sorted(unknown_gates)} in GATES_DOC")

    def is_read(name: str) -> bool:
        return GATES_DOC[GATES[name]][1]

    # (count-table label, section heading, tools)
    groups = [
        (
            "Read-only",
            "Read-only",
            sorted(n for n in tools if is_read(n) and n not in LIVE_PROBE_TOOLS),
        ),
        (
            "Changes state",
            "Changes state",
            sorted(n for n in tools if not is_read(n) and n not in LIVE_PROBE_TOOLS),
        ),
        (
            "Live probe",
            "Live probe (persists nothing, opens a datasource — gated like a write)",
            sorted(LIVE_PROBE_TOOLS),
        ),
    ]
    lines = [
        "# MCP tools",
        "",
        "Every tool DataQ's MCP server exposes at `/mcp`, generated from the server itself — the",
        "gate column is the authorization each tool declares (the same table the RBAC test sweeps",
        "run against), and the description is the opening of what an AI assistant is shown.",
        "",
        "| | Count |",
        "|---|---|",
        f"| Tools | {len(tools)} |",
        *(f"| {label} | {len(names)} |" for label, _, names in groups),
        "",
        "No tool creates, edits or re-credentials a connection: every Admin-only capability is a",
        "connection mutation, and a credential must never transit an LLM.",
        "",
    ]
    for _, heading, names in groups:
        lines += [f"## {heading}", "", "| Tool | Who can call it | What it does |", "|---|---|---|"]
        for n in names:
            lines.append(
                f"| `{n}` | {GATES_DOC[GATES[n]][0]} | "
                f"{_first_paragraph(tools[n].description or '')} |"
            )
        lines.append("")
    lines += [
        "---",
        "",
        "*Generated by `backend/scripts/export_docs_reference.py` — edit the tool docstrings, not "
        + "this page.*",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv
    outputs = {OPENAPI_OUT: build_openapi(), MCP_OUT: build_mcp_tools()}
    if check:
        stale = [p for p, text in outputs.items() if not p.exists() or p.read_text() != text]
        for p in stale:
            print(
                f"{p.relative_to(ROOT)} is stale — "
                "run python -m backend.scripts.export_docs_reference",
                file=sys.stderr,
            )
        return 1 if stale else 0
    for p, text in outputs.items():
        p.write_text(text)
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
