"""created_by: nullable + ON DELETE SET NULL on the three user FKs (#1319)

`connections.created_by`, `suites.created_by` and `schedules.created_by` were the
only user-referencing foreign keys with no `ondelete` policy, so they defaulted to
`NO ACTION`. Every other one already has an explicit policy — `api_keys.user_id`
/ `sessions.user_id` / `shares.user_id` CASCADE; `changed_by`, `owner_user_id`,
`acknowledged_by`, `resolved_by_user_id` and `audit_events.actor_user_id` SET
NULL.

**`SET NULL`, not RESTRICT.** `created_by` is *provenance* — who made this — not
ownership of the row's lifecycle. RESTRICT would make a user un-erasable because
they once created a suite, which is the wrong answer for GDPR Art 17 erasure
(#432), the very feature this unblocks. It also matches the ADR-0041 shape
already in place next door: `audit_events.actor_user_id` is SET NULL with a
denormalized `actor_label`, so attribution survives the delete — which only helps
if the delete can happen at all.

**Why nullable and the FK change ship together, and why that is
backward-compatible.** `SET NULL` requires the column to be nullable, and the two
must be consistent: a nullable column with a `NO ACTION` FK is the same latent
500, and a `SET NULL` FK on a NOT NULL column would fail at delete time instead.
Shipping them apart would leave a window in which one of those states is live.

The pair is safe to deploy in one step because **no NULL can appear before the
new code is running**: there is no user-delete route anywhere in the app
(`api/v1/users.py` has zero mutation routes), so the only producer of a NULL
`created_by` is a cascade that cannot be triggered yet. Code deployed *before*
this migration keeps working unmodified — it writes a non-null value, which a
nullable column accepts — and code deployed *after* tolerates the NULL it still
cannot yet observe. That is the CONTRIBUTING two-step ordering satisfied by the
absence of a producer rather than by splitting the change; recorded here because
"it's just a widen" is exactly the reasoning that gets this wrong.

Widening NOT NULL → NULL is a catalog-only change on Postgres (no table rewrite,
no scan). Dropping and recreating a foreign key takes a brief ACCESS EXCLUSIVE
lock on the child table and re-validates it, which is a scan of the child — all
three are small tables (connections, suites, schedules), so this is cheap; on a
large child table it would not be.

Tested up + down locally against real Postgres, including with rows present.
Rollback: `downgrade()` restores NOT NULL and the policy-less FK. It **fails
loudly if any row has a NULL `created_by`**, which is correct — those rows exist
precisely because a user was erased, and inventing an author for them would be
worse than refusing.

Revision ID: 115c74d4bf26
Revises: ecda713656ac
Create Date: 2026-08-18 00:00:00.000000+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "115c74d4bf26"
down_revision: str | None = "ecda713656ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: (table, constraint name) for each edge. The names are the repo's conventional
#: `fk_<table>_<column>_<referred>` form, as generated by the metadata naming
#: convention — spelled out rather than derived, so this migration keeps working
#: if that convention ever changes.
_EDGES: tuple[tuple[str, str], ...] = (
    ("connections", "fk_connections_created_by_users"),
    ("suites", "fk_suites_created_by_users"),
    ("schedules", "fk_schedules_created_by_users"),
)


def upgrade() -> None:
    for table, constraint in _EDGES:
        op.alter_column(table, "created_by", existing_type=sa.UUID(), nullable=True)
        op.drop_constraint(constraint, table, type_="foreignkey")
        op.create_foreign_key(
            constraint, table, "users", ["created_by"], ["id"], ondelete="SET NULL"
        )


def downgrade() -> None:
    for table, constraint in _EDGES:
        op.drop_constraint(constraint, table, type_="foreignkey")
        op.create_foreign_key(constraint, table, "users", ["created_by"], ["id"])
        # Deliberately NOT backfilled. A NULL here means the creating user was
        # erased (GDPR Art 17), so there is no correct value to restore — this
        # raises rather than inventing an author or silently deleting the row.
        op.alter_column(table, "created_by", existing_type=sa.UUID(), nullable=False)
