"""add FK indexes on join columns (#42)"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf42d364f74b"
down_revision: str | None = "923dab15eb8c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_checks_suite_id", "checks", ["suite_id"], unique=False)
    op.create_index("ix_connections_created_by", "connections", ["created_by"], unique=False)
    op.create_index(
        "ix_pipeline_runs_connection_id", "pipeline_runs", ["connection_id"], unique=False
    )
    op.create_index("ix_results_check_id", "results", ["check_id"], unique=False)
    op.create_index("ix_shares_user_id", "shares", ["user_id"], unique=False)
    op.create_index("ix_suites_connection_id", "suites", ["connection_id"], unique=False)
    op.create_index("ix_suites_created_by", "suites", ["created_by"], unique=False)
    op.create_index("ix_trigger_bindings_suite_id", "trigger_bindings", ["suite_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trigger_bindings_suite_id", table_name="trigger_bindings")
    op.drop_index("ix_suites_created_by", table_name="suites")
    op.drop_index("ix_suites_connection_id", table_name="suites")
    op.drop_index("ix_shares_user_id", table_name="shares")
    op.drop_index("ix_results_check_id", table_name="results")
    op.drop_index("ix_pipeline_runs_connection_id", table_name="pipeline_runs")
    op.drop_index("ix_connections_created_by", table_name="connections")
    op.drop_index("ix_checks_suite_id", table_name="checks")
    # ### end Alembic commands ###
