#!/usr/bin/env bash
# Trust (or stop trusting) the certificate authority of the local prebuilt-image stack, so
# https://localhost:3000 opens without a browser warning.
#
#   scripts/local-ca.sh install      # generate the CA if needed, then trust it (default)
#   scripts/local-ca.sh uninstall    # remove it from the trust stores again
#   scripts/local-ca.sh status       # say whether this machine trusts it
#
# Run it from the directory holding docker-compose.ghcr.yml (or set DATAQ_COMPOSE_FILE), or pass
# --ca <file> to use a CA certificate you already copied out. It needs no source checkout.
#
# The CA is generated by the stack itself and exists only on this machine. Its private key stays
# in a Docker volume; this script handles the public certificate only. Trusting it changes a
# system setting, so the script asks for sudo and says why first. If you decline, or it fails,
# the stack still works: the browser shows a warning you can accept.

set -euo pipefail

CA_NAME="DataQ Local Dev CA"
COMPOSE_FILE="${DATAQ_COMPOSE_FILE:-docker-compose.ghcr.yml}"
LINUX_FILE_STEM="dataq-local-dev-ca"

CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; NC='\033[0m'
step() { echo -e "${CYAN}▶ $1${NC}"; }
ok()   { echo -e "${GREEN}✓ $1${NC}"; }
warn() { echo -e "${YELLOW}! $1${NC}" >&2; }

usage() { sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'; }

command="install"
ca_file=""
while [ $# -gt 0 ]; do
  case "$1" in
    install|uninstall|status) command="$1" ;;
    --ca) shift; ca_file="${1:-}"; [ -n "${ca_file}" ] || { usage; exit 2; } ;;
    -h|--help) usage; exit 0 ;;
    *) usage; exit 2 ;;
  esac
  shift
done

workdir="$(mktemp -d)"
trap 'rm -rf "${workdir}"' EXIT

# ── The CA certificate ────────────────────────────────────────────────────────
# Compose needs these two to parse the file at all; neither is used by the CA step, so a
# placeholder is enough when the caller has not exported them.
compose() {
  OPENBAO_TOKEN="${OPENBAO_TOKEN:-unused}" DATAQ_SIGNIN_EMAIL="${DATAQ_SIGNIN_EMAIL-unused@example.com}" \
    docker compose -f "${COMPOSE_FILE}" "$@"
}

# fetch_ca <generate: yes|no> — put the stack's CA certificate at ${workdir}/ca.pem.
fetch_ca() {
  local generate="$1"
  if [ -n "${ca_file}" ]; then
    [ -r "${ca_file}" ] || { warn "Cannot read ${ca_file}"; return 1; }
    cp "${ca_file}" "${workdir}/ca.pem"
  else
    command -v docker >/dev/null || { warn "docker not found"; return 1; }
    [ -f "${COMPOSE_FILE}" ] || {
      warn "${COMPOSE_FILE} not found here. Run this beside it, set DATAQ_COMPOSE_FILE, or pass --ca <file>."
      return 1
    }
    if [ "${generate}" = "yes" ]; then
      # Idempotent: keeps an existing CA, creates one on a fresh volume.
      compose run --rm --no-deps --quiet-pull local-ca >/dev/null 2>"${workdir}/run.log" || {
        cat "${workdir}/run.log" >&2
        warn "Could not run the stack's CA step"
        return 1
      }
    fi
    compose run --rm --no-deps -T local-ca cat /certs/ca.pem > "${workdir}/ca.pem" 2>/dev/null \
      || { warn "The stack has no CA yet. Start it once, or run: $0 install"; return 1; }
  fi
  grep -q "BEGIN CERTIFICATE" "${workdir}/ca.pem" || { warn "That is not a PEM certificate"; return 1; }
  # Refuse anything that is not this stack's CA: this script must never trust an arbitrary file.
  local subject
  subject="$(openssl x509 -in "${workdir}/ca.pem" -noout -subject -nameopt RFC2253 2>/dev/null || true)"
  [ "${subject}" = "subject=CN=${CA_NAME}" ] || {
    warn "The certificate is not '${CA_NAME}' (${subject:-unreadable}); refusing to trust it."
    return 1
  }
}

fingerprint() { openssl x509 -in "$1" -noout -fingerprint -sha256 | sed 's/.*=//; s/://g'; }

# ── macOS: the System keychain ────────────────────────────────────────────────
MAC_KEYCHAIN="/Library/Keychains/System.keychain"

mac_trusted_fingerprints() {
  security find-certificate -a -c "${CA_NAME}" -Z "${MAC_KEYCHAIN}" 2>/dev/null \
    | sed -n 's/^SHA-256 hash: //p'
}

mac_remove_all() {
  # One per call; a re-created stack leaves an older CA of the same name behind.
  while security find-certificate -c "${CA_NAME}" "${MAC_KEYCHAIN}" >/dev/null 2>&1; do
    sudo security delete-certificate -c "${CA_NAME}" -t "${MAC_KEYCHAIN}" || return 1
  done
}

mac_install() {
  local want; want="$(fingerprint "${workdir}/ca.pem")"
  if mac_trusted_fingerprints | grep -qix "${want}"; then
    ok "Already trusted in the System keychain"
    return 0
  fi
  echo "  Adding '${CA_NAME}' to the System keychain needs your password (sudo)."
  mac_remove_all || return 1
  sudo security add-trusted-cert -d -r trustRoot -k "${MAC_KEYCHAIN}" "${workdir}/ca.pem" || return 1
  ok "Trusted in the System keychain (Safari, Chrome, Edge, curl)"
}

mac_uninstall() {
  if ! security find-certificate -c "${CA_NAME}" "${MAC_KEYCHAIN}" >/dev/null 2>&1; then
    ok "Not in the System keychain"
    return 0
  fi
  echo "  Removing '${CA_NAME}' from the System keychain needs your password (sudo)."
  mac_remove_all || return 1
  ok "Removed from the System keychain"
}

mac_status() {
  if [ -n "$(mac_trusted_fingerprints)" ]; then echo "System keychain: present"; else echo "System keychain: absent"; fi
}

# ── Linux: the system CA bundle ───────────────────────────────────────────────
linux_target() {
  if command -v update-ca-certificates >/dev/null 2>&1; then
    echo "/usr/local/share/ca-certificates/${LINUX_FILE_STEM}.crt"
  elif command -v update-ca-trust >/dev/null 2>&1; then
    echo "/etc/pki/ca-trust/source/anchors/${LINUX_FILE_STEM}.pem"
  fi
}

# linux_refresh [--fresh] — `--fresh` (Debian family) also drops the links of a removed CA.
linux_refresh() {
  if command -v update-ca-certificates >/dev/null 2>&1; then
    as_root update-ca-certificates "$@" >/dev/null 2>&1
  else
    as_root update-ca-trust extract
  fi
}

as_root() { if [ "$(id -u)" -eq 0 ]; then "$@"; else sudo "$@"; fi; }

linux_install() {
  local target; target="$(linux_target)"
  if [ -z "${target}" ]; then
    warn "No update-ca-certificates or update-ca-trust here; add ${workdir}/ca.pem to your system's CA store by hand."
    return 1
  fi
  if [ -f "${target}" ] && cmp -s "${target}" "${workdir}/ca.pem"; then
    ok "Already in the system CA store"
    return 0
  fi
  echo "  Adding '${CA_NAME}' to the system CA store needs root (sudo)."
  as_root install -m 0644 "${workdir}/ca.pem" "${target}" || return 1
  linux_refresh || return 1
  ok "Trusted in the system CA store (curl and most command-line clients)"
}

linux_uninstall() {
  local target; target="$(linux_target)"
  if [ -z "${target}" ] || [ ! -f "${target}" ]; then
    ok "Not in the system CA store"
    return 0
  fi
  echo "  Removing '${CA_NAME}' from the system CA store needs root (sudo)."
  as_root rm -f "${target}" || return 1
  linux_refresh --fresh || return 1
  ok "Removed from the system CA store"
}

linux_status() {
  local target; target="$(linux_target)"
  if [ -n "${target}" ] && [ -f "${target}" ]; then echo "System CA store: present"; else echo "System CA store: absent"; fi
}

# ── NSS stores: Firefox everywhere, and Chrome on Linux ───────────────────────
nss_dirs() {
  local dir
  for dir in "${HOME}/Library/Application Support/Firefox/Profiles"/* "${HOME}/.mozilla/firefox"/* "${HOME}/.pki/nssdb"; do
    [ -f "${dir}/cert9.db" ] && echo "${dir}"
  done
  return 0
}

nss_each() {
  local action="$1" dir found=0
  if ! command -v certutil >/dev/null 2>&1; then
    [ -n "$(nss_dirs)" ] || return 0
    case "${action}" in
      install) warn "Firefox keeps its own trust store and 'certutil' (NSS tools) is not installed. In Firefox: Settings → Privacy & Security → View Certificates → Authorities → Import, and pick the CA file (copy it out with: docker compose -f ${COMPOSE_FILE} cp frontend:/certs/ca.pem .)" ;;
      uninstall) warn "Firefox keeps its own trust store: remove '${CA_NAME}' under Settings → Privacy & Security → View Certificates → Authorities." ;;
    esac
    return 0
  fi
  while IFS= read -r dir; do
    [ -n "${dir}" ] || continue
    found=1
    case "${action}" in
      install)
        certutil -D -n "${CA_NAME}" -d "sql:${dir}" >/dev/null 2>&1 || true
        if certutil -A -n "${CA_NAME}" -t "C,," -i "${workdir}/ca.pem" -d "sql:${dir}"; then
          ok "Trusted in the browser store ${dir}"
        else
          warn "Could not add it to ${dir} (close the browser and re-run)"
        fi ;;
      uninstall)
        if certutil -D -n "${CA_NAME}" -d "sql:${dir}" >/dev/null 2>&1; then ok "Removed from ${dir}"; fi ;;
      status)
        if certutil -L -n "${CA_NAME}" -d "sql:${dir}" >/dev/null 2>&1; then echo "Browser store ${dir}: present"; else echo "Browser store ${dir}: absent"; fi ;;
    esac
  done < <(nss_dirs)
  [ "${found}" -eq 1 ] || true
}

# ── Dispatch ──────────────────────────────────────────────────────────────────
os="$(uname -s)"
declined() {
  warn "The CA was not $1. The stack still works: your browser will show a certificate warning you can accept."
}

case "${command}" in
  install)
    step "Trusting the local stack's certificate authority"
    fetch_ca yes || { declined "trusted"; exit 0; }
    case "${os}" in
      Darwin) mac_install || declined "trusted" ;;
      Linux)  linux_install || declined "trusted" ;;
      *)
        cp "${workdir}/ca.pem" "./${LINUX_FILE_STEM}.pem"
        warn "On Windows, from an elevated prompt: certutil -addstore Root ${LINUX_FILE_STEM}.pem (written to this directory)" ;;
    esac
    nss_each install
    ;;
  uninstall)
    step "Removing the local stack's certificate authority from the trust stores"
    case "${os}" in
      Darwin) mac_uninstall || declined "removed" ;;
      Linux)  linux_uninstall || declined "removed" ;;
      *) warn "On Windows, from an elevated prompt: certutil -delstore Root \"${CA_NAME}\"" ;;
    esac
    nss_each uninstall
    ;;
  status)
    case "${os}" in
      Darwin) mac_status ;;
      Linux)  linux_status ;;
      *) echo "Check with: certutil -store Root \"${CA_NAME}\"" ;;
    esac
    nss_each status
    ;;
esac
